#!/bin/bash
# Ablation round 3: 2 follow-up experiments on the round-2 winner (fastvit_sa12).
# Hardware: 2x RTX 2080 (11 GB VRAM each) -> one experiment per GPU, both at once.
#
# Round-2 winner: fastvit_sa12, focal a=0.75 g=2.0, neg_skip=0.5, EMA 0.999
#   (exp07: F1 0.8958, recall 0.877, precision 0.916, acc 99.02%).
#
# This round changes ONLY the data pipeline, keeping the winning recipe fixed:
#   A) val_split = val_suffix:   validate on the hand-picked *_val videos only,
#      train on everything else (instead of the fold-3 bucket). Tells us how the
#      model does on a curated held-out set rather than a random fold.
#   B) num_frames=3 + target_fps=30: 3-frame early-fusion input, fps-normalized so
#      60fps clips skip one frame (stride 2) and 30fps clips use consecutive frames
#      (stride 1). Gives the model short-term motion context. in_chans becomes 9;
#      timm adapts the pretrained first conv automatically.
#
# Requires fps_map.json in the repo root (generated by:
#   python training_set.py --fps_map --video_dir videos --fps_map_out fps_map.json)
#
# NOTE on pretrained weights: fastvit_sa12 was already cached in round 2. If the
# node is offline, HF_HUB_OFFLINE=1 below uses the cache.

export HF_HUB_OFFLINE=1

mkdir -p ablation_logs3

train_model() {
  # args: $1=gpu $2=batch $3=num_frames $4=target_fps $5=val_split $6=tag
  CUDA_VISIBLE_DEVICES=$1 python train_classifier.py \
    --model_name fastvit_sa12 \
    --batch_size "$2" \
    --lr 1e-4 \
    --epochs 30 \
    --fold 3 \
    --num_workers 8 \
    --input_width 256 \
    --input_height 256 \
    --class_balance focal \
    --focal_alpha 0.75 \
    --focal_gamma 2.0 \
    --neg_skip_prob 0.35 \
    --num_frames "$3" \
    --target_fps "$4" \
    --val_split "$5" \
    --ema \
    --ema_decay 0.999 \
    --output_dir "trainings3/$6" \
    > "ablation_logs3/$6.log" 2>&1
}

# ---------------------------------------------------------------------------
# RUN:    ./run_ablation_experiments3.sh        (runs both, one per GPU)
# WATCH:  tail -f ablation_logs3/*.log
# STOP:   pkill -f train_classifier.py
# Config: train_model  gpu  batch  num_frames  target_fps  val_split  tag
# Batch sizes target 11 GB at 256x256 (no AMP); shrink if you OOM.
# ---------------------------------------------------------------------------

echo "=== Round 3: val_suffix split + 3-frame fps-normalized input ==="

# Two clean A/B pairs (1-frame vs 3-frame on the SAME val set):
#   fold split:       exp19 (nf1) vs exp18 (nf3)   <- isolates effect of motion frames
#   val_suffix split: exp17 (nf1) vs exp20 (nf3)   <- same, on the curated *_val set
#
# DONE already (do not rerun):
#   train_model 0 64 1 0  val_suffix exp17_fastvit_sa12_valsuffix   (EMA F1 0.8729)
#   train_model 1 64 3 30 fold       exp18_fastvit_sa12_nf3fps30    (EMA F1 0.8536)

# exp19: 1-frame baseline on the CURRENT fold-3 val set -> matched baseline for exp18.
# train_model 1 64 1 0  fold       exp19_fastvit_sa12_nf1fold      &
# wait
# exp20: 3-frame fps-normalized on the val_suffix set -> matched comparison for exp17.
# train_model 1 64 3 30 val_suffix exp20_fastvit_sa12_nf3fps30_valsuffix &

# wait

train_model 1 64 1 0  val_suffix exp21_fastvit_sa12_valsuffix_more_data_ns0.35 &

wait
echo "Round 3 follow-up finished. Logs in ablation_logs3/, models in trainings3/."
